CodeMirror.defineMode("less",function(p){function c(a,b){d=b;return a}function g(a,b){var e=a.next();if("@"==e)return a.eatWhile(/[\w\-]/),c("meta",a.current());if("/"==e&&a.eat("*"))return b.tokenize=k,k(a,b);if("<"==e&&a.eat("!"))return b.tokenize=l,l(a,b);if("="==e)c(null,"compare");else{if("|"==e&&a.eat("="))return c(null,"compare");if('"'==e||"'"==e)return b.tokenize=q(e),b.tokenize(a,b);if("/"==e){if(a.eat("/"))return b.tokenize=m,m(a,b);if("string"==d||"("==d)return c("string","string");if(void 0!==
b.stack[b.stack.length-1])return c(null,e);a.eatWhile(/[\a-zA-Z0-9\-_.\s]/);if(/\/|\)|#/.test(a.peek()||a.eatSpace()&&")"===a.peek())||a.eol())return c("string","string")}else{if("!"==e)return a.match(/^\s*\w*/),c("keyword","important");if(/\d/.test(e))return a.eatWhile(/[\w.%]/),c("number","unit");if(/[,+<>*\/]/.test(e))return"="==a.peek()||"a"==d?c("string","string"):","===e?c(null,e):c(null,"select-op");if(/[;{}:\[\]()~\|]/.test(e)){if(":"==e)return a.eatWhile(/[a-z\\\-]/),h.test(a.current())?
c("tag","tag"):":"==a.peek()?(a.next(),a.eatWhile(/[a-z\\\-]/),a.current().match(/\:\:\-(o|ms|moz|webkit)\-/)?c("string","string"):h.test(a.current().substring(1))?c("tag","tag"):c(null,e)):c(null,e);if("~"==e){if("r"==d)return c("string","string")}else return c(null,e)}else{if("."==e){if("("==d)return c("string","string");a.eatWhile(/[\a-zA-Z0-9\-_]/);" "===a.peek()&&a.eatSpace();return")"===a.peek()||":"===d||"rule"===b.stack[b.stack.length-1]&&null===a.peek().match(/{|,|\+|\(/)?c("number","unit"):
c("tag","tag")}if("#"==e){a.eatWhile(/[A-Za-z0-9]/);if(4==a.current().length||7==a.current().length){if(null!=a.current().match(/[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3}/,!1)){if(a.current().substring(1)!=a.current().match(/[A-Fa-f0-9]{6}|[A-Fa-f0-9]{3}/,!1))return c("atom","tag");a.eatSpace();return/[\/<>.(){!$%^&*_\-\\?=+\|#'~`]/.test(a.peek())?"select-op"===d?c("number","unit"):c("atom","tag"):"}"==a.peek()?c("number","unit"):/[a-zA-Z\\]/.test(a.peek())?c("atom","tag"):a.eol()?c("atom","tag"):c("number",
"unit")}a.eatWhile(/[\w\\\-]/);return c("atom",a.current())}a.eatWhile(/[\w\\\-]/);return c("atom",a.current())}if("&"==e)return a.eatWhile(/[\w\-]/),c(null,e);a.eatWhile(/[\w\\\-_%.{]/);if(null!==a.current().match(/\\/)){if("\\"===a.current().charAt(a.current().length-1)){for(a.eat(/\'|\"|\)|\(/);a.eatWhile(/[\w\\\-_%.{]/);)a.eat(/\'|\"|\)|\(/);return c("string",a.current())}}else{if("string"==d){if("{"===b.stack[b.stack.length-1]&&":"===a.peek())return c("variable","variable");"/"===a.peek()&&a.eatWhile(/[\w\\\-_%.{:\/]/);
return c(d,a.current())}if(null!=a.current().match(/(^http$|^https$)/))return a.eatWhile(/[\w\\\-_%.{:\/]/),"/"===a.peek()&&a.eatWhile(/[\w\\\-_%.{:\/]/),c("string","string");if("<"==a.peek()||">"==a.peek()||"+"==a.peek())return"("!==d||"n"!==a.current()&&"-n"!==a.current()?c("tag","tag"):c("string",a.current());if(/\(/.test(a.peek()))return"when"===a.current()?c("variable","variable"):"@media"===b.stack[b.stack.length-1]&&"and"===a.current()?c("variable",a.current()):c(null,e);if("/"==a.peek()&&
void 0!==b.stack[b.stack.length-1])return"/"===a.peek()&&a.eatWhile(/[\w\\\-_%.{:\/]/),c("string",a.current());if(a.current().match(/\-\d|\-.\d/))return c("number","unit");if(/\/|[\s\)]/.test(a.peek()||a.eol()||a.eatSpace()&&"/"==a.peek())&&-1!==a.current().indexOf(".")){if("{"==a.current().substring(a.current().length-1,a.current().length))return a.backUp(1),c("tag","tag");a.eatSpace();return/[{<>.a-zA-Z\/]/.test(a.peek())||a.eol()?c("tag","tag"):c("string","string")}if(a.eol()||"["==a.peek()||"#"==
a.peek()||"tag"==d){if("{"==a.current().substring(a.current().length-1,a.current().length))a.backUp(1);else{if("border-color"===b.stack[b.stack.length-1]||"background-position"===b.stack[b.stack.length-1]||"font-family"===b.stack[b.stack.length-1])return c(null,a.current());if("tag"!==d)if(":"!==d&&"unit"!==d||"rule"!==b.stack[b.stack.length-1]){if("rule"===b.stack[b.stack.length-1]&&"tag"===d)return c("string",a.current());if(";"===b.stack[b.stack.length-1]&&":"===d)return c(null,a.current());if("#"===
a.peek()&&void 0!==d&&null===d.match(/\+|,|tag|select\-op|}|{|;/g))return c("string",a.current());if("variable"===d)return c(null,a.current());if("{"===b.stack[b.stack.length-1]&&"comment"===d)return c("variable",a.current());if(0!==b.stack.length||";"!==d&&"comment"!==d){if(("{"===b.stack[b.stack.length-1]||";"===d)&&"@media{"!==b.stack[b.stack.length-1]||"{"===b.stack[b.stack.length-2]&&";"===b.stack[b.stack.length-1])return c("variable",a.current())}else return c("tag",a.current())}else return c(null,
a.current())}return c("tag","tag")}if("compare"==d||"a"==d||"("==d)return c("string","string");if("|"==d||"-"==a.current()||"["==d)return"|"==d&&null!==a.peek().match(/\]|=|\~/)?c("number",a.current()):"|"==d?c("tag","tag"):"["==d?(a.eatWhile(/\w\-/),c("number",a.current())):c(null,e);if(":"==a.peek()||a.eatSpace()&&":"==a.peek()){a.next();if(e=":"==a.peek()?!0:!1)a.backUp(1);else{var f=a.pos,g=a.current().length;a.eatWhile(/[a-z\\\-]/);var n=a.pos;if(null!=a.current().substring(g-1).match(h))return a.backUp(n-
(f-1)),c("tag","tag");a.backUp(n-(f-1))}return e?c("tag","tag"):c("variable","variable")}if("font-family"===b.stack[b.stack.length-1]||"background-position"===b.stack[b.stack.length-1]||"border-color"===b.stack[b.stack.length-1])return c(null,null);if(null===b.stack[b.stack.length-1]&&":"===d)return c(null,a.current());if(/\^|\$/.test(a.current())&&null!==a.peek().match(/\~|=/))return c("string","string");if("unit"===d&&"rule"===b.stack[b.stack.length-1]||"unit"===d&&";"===b.stack[b.stack.length-
1]||")"===d&&"rule"===b.stack[b.stack.length-1]||null!==d.match("@")&&"rule"===b.stack[b.stack.length-1])return c(null,"unit");if(";"!==d&&"}"!==d&&","!==d||";"!==b.stack[b.stack.length-1]){if(";"===d&&void 0!==a.peek()&&null===a.peek().match(/{|./)||";"===d&&a.eatSpace()&&null===a.peek().match(/{|./))return c("variable",a.current());if(("@media"!==d||"@media"!==b.stack[b.stack.length-1])&&"@namespace"!==d){if("{"===d&&";"===b.stack[b.stack.length-1]&&"{"===a.peek())return c("tag","tag");if("{"!==
d&&":"!==d||";"!==b.stack[b.stack.length-1]){if("{"===b.stack[b.stack.length-1]&&a.eatSpace()&&null===a.peek().match(/.|#/)||"select-op"===d||"rule"===b.stack[b.stack.length-1]&&","===d||"variable"===d&&"rule"===b.stack[b.stack.length-1]||a.eatSpace()&&"{"===a.peek()||a.eol()||"{"===a.peek())return c("tag","tag");if(")"!==d||"and"!=a.current()&&"and "!=a.current())if(")"!==d||"when"!=a.current()&&"when "!=a.current()){if(")"===d||"comment"===d||"{"===d||a.sol()||a.eatSpace()&&"#"===a.peek()||"#"===
a.peek()||0===b.stack.length||";"===d&&void 0!==a.peek()&&null!==a.peek().match(/^[.|\#]/g))return c("tag","tag");if(":"===d)return a.eatSpace(),c(null,a.current());if("and "===a.current()||"and"===a.current()||";"===d&&"{"===b.stack[b.stack.length-1])return c("variable",a.current());if("rule"===b.stack[b.stack.length-1])return c(null,a.current())}else return c("variable","variable");else return c("variable","variable")}else return c(null,a.current())}}return c("tag",a.current())}}}}}function m(a,
b){a.skipToEnd();b.tokenize=g;return c("comment","comment")}function k(a,b){for(var d=!1,f;null!=(f=a.next());){if(d&&"/"==f){b.tokenize=g;break}d="*"==f}return c("comment","comment")}function l(a,b){for(var d=0,f;null!=(f=a.next());){if(2<=d&&">"==f){b.tokenize=g;break}d="-"==f?d+1:0}return c("comment","comment")}function q(a){return function(b,d){for(var f=!1,h;null!=(h=b.next())&&(h!=a||f);)f=!f&&"\\"==h;f||(d.tokenize=g);return c("string","string")}}var r=p.indentUnit,d,h=/(^\:root$|^\:nth\-child$|^\:nth\-last\-child$|^\:nth\-of\-type$|^\:nth\-last\-of\-type$|^\:first\-child$|^\:last\-child$|^\:first\-of\-type$|^\:last\-of\-type$|^\:only\-child$|^\:only\-of\-type$|^\:empty$|^\:link|^\:visited$|^\:active$|^\:hover$|^\:focus$|^\:target$|^\:lang$|^\:enabled^\:disabled$|^\:checked$|^\:first\-line$|^\:first\-letter$|^\:before$|^\:after$|^\:not$|^\:required$|^\:invalid$)/;
return{startState:function(a){return{tokenize:g,baseIndent:a||0,stack:[]}},token:function(a,b){if(a.eatSpace())return null;var e=b.tokenize(a,b),f=b.stack[b.stack.length-1];"hash"==d&&"rule"==f?e="atom":"variable"==e&&("rule"==f?e=null:f&&"@media{"!=f||(e="when"==a.current()?"variable":/[\s,|\s\)|\s]/.test(a.peek())?"tag":d));"rule"==f&&/^[\{\};]$/.test(d)&&b.stack.pop();"{"==d?"@media"==f?b.stack[b.stack.length-1]="@media{":b.stack.push("{"):"}"==d?b.stack.pop():"@media"==d?b.stack.push("@media"):
"font-family"===a.current()?b.stack[b.stack.length-1]="font-family":"background-position"===a.current()?b.stack[b.stack.length-1]="background-position":"border-color"===a.current()?b.stack[b.stack.length-1]="border-color":"{"==f&&"comment"!=d&&"tag"!==d?b.stack.push("rule"):":"===a.peek()&&null===a.current().match(/@|#/)&&(e=d);if(";"===d&&("font-family"==b.stack[b.stack.length-1]||"background-position"==b.stack[b.stack.length-1]||"border-color"==b.stack[b.stack.length-1]))b.stack[b.stack.length-
1]=a.current();else if("tag"===d&&")"===a.peek()&&null===a.current().match(/\:/))e=d=null;else if("variable"===d&&")"===a.peek()||"variable"===d&&a.eatSpace()&&")"===a.peek())return c(null,a.current());return e},indent:function(a,b){var c=a.stack.length;/^\}/.test(b)?c-="rule"===a.stack[a.stack.length-1]?2:1:"{"===a.stack[a.stack.length-2]&&(c-="rule"===a.stack[a.stack.length-1]?1:0);return a.baseIndent+c*r},electricChars:"}",blockCommentStart:"/*",blockCommentEnd:"*/",lineComment:"//"}});
CodeMirror.defineMIME("text/x-less","less");CodeMirror.mimeModes.hasOwnProperty("text/css")||CodeMirror.defineMIME("text/css","less");
