CodeMirror.defineMode("javascript",function(W,q){function K(a,d){for(var b=!1,e;null!=(e=a.next());){if(e==d&&!b)return!1;b=!b&&"\\"==e}return b}function n(a,d,b){u=a;v=b;return d}function w(a,d){var b=a.next();if('"'==b||"'"==b)return b=X(b),d.tokenize=b,b(a,d);if("."==b&&a.match(/^\d+(?:[eE][+\-]?\d+)?/))return n("number","number");if(/[\[\]{}\(\),;\:\.]/.test(b))return n(b);if("0"==b&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),n("number","number");if(/\d/.test(b))return a.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),
n("number","number");if("/"==b){if(a.eat("*"))return b=B,d.tokenize=b,b(a,d);if(a.eat("/"))return a.skipToEnd(),n("comment","comment");if("operator"==d.lastType||"keyword c"==d.lastType||/^[\[{}\(,;:]$/.test(d.lastType))return K(a,"/"),a.eatWhile(/[gimy]/),n("regexp","string-2");a.eatWhile(C);return n("operator",null,a.current())}if("#"==b)return a.skipToEnd(),n("error","error");if(C.test(b))return a.eatWhile(C),n("operator",null,a.current());a.eatWhile(/[\w\$_]/);var b=a.current(),e=L.propertyIsEnumerable(b)&&
L[b];return e&&"."!=d.lastType?n(e.type,e.style,b):n("variable","variable",b)}function X(a){return function(d,b){K(d,a)||(b.tokenize=w);return n("string","string")}}function B(a,d){for(var b=!1,e;e=a.next();){if("/"==e&&b){d.tokenize=w;break}b="*"==e}return n("comment","comment")}function M(a,d,b,e,c,f){this.indented=a;this.column=d;this.type=b;this.prev=c;this.info=f;null!=e&&(this.align=e)}function m(){for(var a=arguments.length-1;0<=a;a--)f.cc.push(arguments[a])}function c(){m.apply(null,arguments);
return!0}function D(a){function d(b){for(;b;b=b.next)if(b.name==a)return!0;return!1}var b=f.state;b.context?(f.marked="def",d(b.localVars)||(b.localVars={name:a,next:b.localVars})):d(b.globalVars)||(b.globalVars={name:a,next:b.globalVars})}function N(){f.state.context={prev:f.state.context,vars:f.state.localVars};f.state.localVars=Y}function O(){f.state.localVars=f.state.context.vars;f.state.context=f.state.context.prev}function g(a,d){var b=function(){var b=f.state,c=b.indented;"stat"==b.lexical.type&&
(c=b.lexical.indented);b.lexical=new M(c,f.stream.column(),a,null,b.lexical,d)};b.lex=!0;return b}function h(){var a=f.state;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=a.lexical.indented),a.lexical=a.lexical.prev)}function k(a){return function(d){return d==a?c():";"==a?m():c(arguments.callee)}}function p(a){return"var"==a?c(g("vardef"),E,k(";"),h):"keyword a"==a?c(g("form"),l,p,h):"keyword b"==a?c(g("form"),p,h):"{"==a?c(g("}"),F,h):";"==a?c():"if"==a?c(g("form"),l,p,h,P):"function"==a?c(x):
"for"==a?c(g("form"),k("("),g(")"),Z,k(")"),h,p,h):"variable"==a?c(g("stat"),$):"switch"==a?c(g("form"),l,g("}","switch"),k("{"),F,h,h):"case"==a?c(l,k(":")):"default"==a?c(k(":")):"catch"==a?c(g("form"),N,k("("),Q,k(")"),p,h,O):m(g("stat"),l,k(";"),h)}function l(a){return R(a,!1)}function r(a){return R(a,!0)}function R(a,d){var b=d?G:y;return S.hasOwnProperty(a)?c(b):"function"==a?c(x):"keyword c"==a?c(d?aa:H):"("==a?c(g(")"),H,k(")"),h,b):"operator"==a?c(d?r:l):"["==a?c(g("]"),z(r,"]"),h,b):"{"==
a?c(g("}"),z(ba,"}"),h,b):c()}function H(a){return a.match(/[;\}\)\],]/)?m():m(l)}function aa(a){return a.match(/[;\}\)\],]/)?m():m(r)}function y(a,d){return","==a?c(l):G(a,d,!1)}function G(a,d,b){var e=!1==b?y:G;b=!1==b?l:r;if("operator"==a)return/\+\+|--/.test(d)?c(e):"?"==d?c(l,k(":"),b):c(b);if(";"!=a){if("("==a)return c(g(")","call"),z(r,")"),h,e);if("."==a)return c(ca,e);if("["==a)return c(g("]"),H,k("]"),h,e)}}function $(a){return":"==a?c(h,p):m(y,k(";"),h)}function ca(a){if("variable"==a)return f.marked=
"property",c()}function ba(a,d){if("variable"==a){if(f.marked="property","get"==d||"set"==d)return c(da)}else if("number"==a||"string"==a)f.marked=a+" property";if(S.hasOwnProperty(a))return c(k(":"),r)}function da(a){if(":"==a)return c(l);if("variable"!=a)return c(k(":"),l);f.marked="property";return c(x)}function z(a,d){function b(e){return","==e?(e=f.state.lexical,"call"==e.info&&(e.pos=(e.pos||0)+1),c(a,b)):e==d?c():c(k(d))}return function(e){return e==d?c():m(a,b)}}function F(a){return"}"==a?
c():m(p,F)}function T(a){return":"==a?c(ea):m()}function ea(a){return"variable"==a?(f.marked="variable-3",c()):m()}function E(a,d){return"variable"==a?(D(d),I?c(T,J):c(J)):m()}function J(a,d){if("="==d)return c(r,J);if(","==a)return c(E)}function P(a,d){if("keyword b"==a&&"else"==d)return c(g("form"),p,h)}function Z(a){return"var"==a?c(E,k(";"),A):";"==a?c(A):"variable"==a?c(fa):m(l,k(";"),A)}function fa(a,d){return"in"==d?c(l):c(y,A)}function A(a,d){return";"==a?c(U):"in"==d?c(l):m(l,k(";"),U)}function U(a){")"!=
a&&c(l)}function x(a,d){if("variable"==a)return D(d),c(x);if("("==a)return c(g(")"),N,z(Q,")"),h,p,O)}function Q(a,d){if("variable"==a)return D(d),I?c(T):c()}var s=W.indentUnit,V=q.statementIndent,t=q.json,I=q.typescript,L=function(){function a(a){return{type:a,style:"keyword"}}var d=a("keyword a"),b=a("keyword b"),e=a("keyword c"),c=a("operator"),f={type:"atom",style:"atom"},d={"if":a("if"),"while":d,"with":d,"else":b,"do":b,"try":b,"finally":b,"return":e,"break":e,"continue":e,"new":e,"delete":e,
"throw":e,"var":a("var"),"const":a("var"),let:a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),"switch":a("switch"),"case":a("case"),"default":a("default"),"in":c,"typeof":c,"instanceof":c,"true":f,"false":f,"null":f,undefined:f,NaN:f,Infinity:f,"this":a("this")};if(I){var b={type:"variable",style:"variable-3"},b={"interface":a("interface"),"class":a("class"),"extends":a("extends"),constructor:a("constructor"),"public":a("public"),"private":a("private"),"protected":a("protected"),
"static":a("static"),"super":a("super"),string:b,number:b,bool:b,any:b},h;for(h in b)d[h]=b[h]}return d}(),C=/[+\-*&%=<>!?|~^]/,u,v,S={atom:!0,number:!0,variable:!0,string:!0,regexp:!0,"this":!0},f={state:null,column:null,marked:null,cc:null},Y={name:"this",next:{name:"arguments"}};h.lex=!0;return{startState:function(a){return{tokenize:w,lastType:null,cc:[],lexical:new M((a||0)-s,0,"block",!1),localVars:q.localVars,globalVars:q.globalVars,context:q.localVars&&{vars:q.localVars},indented:0}},token:function(a,
d){a.sol()&&(d.lexical.hasOwnProperty("align")||(d.lexical.align=!1),d.indented=a.indentation());if(d.tokenize!=B&&a.eatSpace())return null;var b=d.tokenize(a,d);if("comment"==u)return b;d.lastType="operator"!=u||"++"!=v&&"--"!=v?u:"incdec";a:{var c=u,h=v,g=d.cc;f.state=d;f.stream=a;f.marked=null;f.cc=g;d.lexical.hasOwnProperty("align")||(d.lexical.align=!0);for(;;)if((g.length?g.pop():t?l:p)(c,h)){for(;g.length&&g[g.length-1].lex;)g.pop()();if(f.marked){b=f.marked;break a}if(c="variable"==c)b:{for(c=
d.localVars;c;c=c.next)if(c.name==h){c=!0;break b}c=void 0}if(c){b="variable-2";break a}break a}b=void 0}return b},indent:function(a,c){if(a.tokenize==B)return CodeMirror.Pass;if(a.tokenize!=w)return 0;for(var b=c&&c.charAt(0),e=a.lexical,f=a.cc.length-1;0<=f;--f){var g=a.cc[f];if(g==h)e=e.prev;else if(g!=P||/^else\b/.test(c))break}"stat"==e.type&&"}"==b&&(e=e.prev);V&&(")"==e.type&&"stat"==e.prev.type)&&(e=e.prev);f=e.type;g=b==f;return"vardef"==f?e.indented+("operator"==a.lastType||","==a.lastType?
4:0):"form"==f&&"{"==b?e.indented:"form"==f?e.indented+s:"stat"==f?e.indented+("operator"==a.lastType||","==a.lastType?V||s:0):"switch"!=e.info||g||!1==q.doubleIndentSwitch?e.align?e.column+(g?0:1):e.indented+(g?0:s):e.indented+(/^(?:case|default)\b/.test(c)?s:2*s)},electricChars:":{}",blockCommentStart:t?null:"/*",blockCommentEnd:t?null:"*/",lineComment:t?null:"//",fold:"brace",helperType:t?"json":"javascript",jsonMode:t}});CodeMirror.defineMIME("text/javascript","javascript");
CodeMirror.defineMIME("text/ecmascript","javascript");CodeMirror.defineMIME("application/javascript","javascript");CodeMirror.defineMIME("application/ecmascript","javascript");CodeMirror.defineMIME("application/json",{name:"javascript",json:!0});CodeMirror.defineMIME("application/x-json",{name:"javascript",json:!0});CodeMirror.defineMIME("text/typescript",{name:"javascript",typescript:!0});CodeMirror.defineMIME("application/typescript",{name:"javascript",typescript:!0});
