(function(){function x(a){k.push(a);50<k.length&&k.shift()}function D(a){return k[k.length-(a?Math.min(a,1):1)]||""}function L(){1<k.length&&k.pop();return D()}function r(a,b,c,d,e){null==e&&(e=a.getRange(b,c));d&&p&&p.cm==a&&b.line==p.pos.line&&b.ch==p.pos.ch&&a.isClean(p.gen)?k.length?k[k.length-1]+=e:x(e):x(e);a.replaceRange("",b,c,"+delete");p=d?{cm:a,pos:b,gen:a.changeGeneration()}:null}function n(a,b,c){return a.findPosH(b,c,"char",!0)}function s(a,b,c){return a.findPosH(b,c,"word",!0)}function t(a,
b,c){return a.findPosV(b,c,"line",a.doc.sel.goalColumn)}function u(a,b,c){return a.findPosV(b,c,"page",a.doc.sel.goalColumn)}function E(a,b,c){var d=b.line,e=a.getLine(d);b=/\S/.test(0>c?e.slice(0,b.ch):e.slice(b.ch));for(var f=a.firstLine(),g=a.lastLine();;){d+=c;if(d<f||d>g)return a.clipPos(h(d-c,0>c?0:null));e=a.getLine(d);if(/\S/.test(e))b=!0;else if(b)return h(d,0)}}function v(a,b,c){var d=b.line,e=b.ch;b=a.getLine(b.line);for(var f=!1;;){var g=b.charAt(e+(0>c?-1:0));if(g){if(f&&/[!?.]/.test(g))return h(d,
e+(0<c?1:0));f||(f=/\w/.test(g));e+=c}else{if(d==(0>c?a.firstLine():a.lastLine()))return h(d,e);b=a.getLine(d+c);if(!/\S/.test(b))return h(d,e);d+=c;e=0>c?b.length:0}}}function l(a,b,c){var d;if(a.findMatchingBracket&&(d=a.findMatchingBracket(b,!0))&&d.match&&(d.forward?1:-1)==c)return 0<c?h(d.to.line,d.to.ch+1):d.to;for(var e=!0;;e=!1){var f=a.getTokenAt(b);d=h(b.line,0>c?f.start:f.end);if(e&&0<c&&f.end==b.ch||!/\w/.test(f.string)){e=a.findPosH(d,c,"char");if(d.line==e.line&&d.ch==e.ch)return b;
b=e}else return d}}function q(a,b){var c=a.state.emacsPrefix;if(!c)return b?null:1;y(a);return"-"==c?-1:Number(c)}function g(a){var b="string"==typeof a?function(b){b.execCommand(a)}:a;return function(a){var d=q(a);b(a);for(var e=1;e<d;++e)b(a)}}function z(a,b,c){var d=a.getCursor(),e=q(a);0>e&&(c=-c,e=-e);for(var f=0;f<e;++f){var g=b(a,d,c);if(g.line==d.line&&g.ch==d.ch)break;d=g}return d}function f(a,b){var c=function(c){c.extendSelection(z(c,a,b))};c.motion=!0;return c}function m(a,b,c){r(a,a.getCursor(),
z(a,b,c),!0)}function F(a,b){a.state.emacsPrefix?"-"!=b&&(a.state.emacsPrefix+=b):(a.state.emacsPrefix=b,a.on("keyHandled",G),a.on("inputRead",H))}function G(a,b){a.state.emacsPrefixMap||I.hasOwnProperty(b)||y(a)}function y(a){a.state.emacsPrefix=null;a.off("keyHandled",G);a.off("inputRead",H)}function H(a,b){var c=q(a);if(1<c&&"+input"==b.origin){for(var d=b.text.join("\n"),e="",f=1;f<c;++f)e+=d;a.replaceSelection(e,"end","+input")}}function w(a,b){if("string"!=typeof b||!/^\d$/.test(b)&&"Ctrl-U"!=
b)a.removeKeyMap(A),a.state.emacsPrefixMap=!1,a.off("keyHandled",w),a.off("inputRead",w)}function J(a){a.setCursor(a.getCursor());a.setExtending(!0);a.on("change",function(){a.setExtending(!1)})}function M(a,b,c){a.openDialog?a.openDialog(b+': <input type="text" style="width: 10em"/>',c,{bottom:!0}):c(prompt(b,""))}function B(a,b){var c=a.getCursor(),d=a.findPosH(c,1,"word");a.replaceRange(b(a.getRange(c,d)),c,d);a.setCursor(d)}function K(a){A[a]=function(b){F(b,a)};N["Ctrl-"+a]=function(b){F(b,a)};
I["Ctrl-"+a]=!0}var h=CodeMirror.Pos,k=[],p=null,I={"Alt-G":!0,"Ctrl-X":!0,"Ctrl-Q":!0,"Ctrl-U":!0},N=CodeMirror.keyMap.emacs={"Ctrl-W":function(a){r(a,a.getCursor("start"),a.getCursor("end"))},"Ctrl-K":g(function(a){var b=a.getCursor(),c=a.clipPos(h(b.line)),d=a.getRange(b,c);/\S/.test(d)||(d+="\n",c=h(b.line+1,0));r(a,b,c,!0,d)}),"Alt-W":function(a){x(a.getSelection())},"Ctrl-Y":function(a){var b=a.getCursor();a.replaceRange(D(q(a)),b,b,"paste");a.setSelection(b,a.getCursor())},"Alt-Y":function(a){a.replaceSelection(L())},
"Ctrl-Space":J,"Ctrl-Shift-2":J,"Ctrl-F":f(n,1),"Ctrl-B":f(n,-1),Right:f(n,1),Left:f(n,-1),"Ctrl-D":function(a){m(a,n,1)},Delete:function(a){m(a,n,1)},"Ctrl-H":function(a){m(a,n,-1)},Backspace:function(a){m(a,n,-1)},"Alt-F":f(s,1),"Alt-B":f(s,-1),"Alt-D":function(a){m(a,s,1)},"Alt-Backspace":function(a){m(a,s,-1)},"Ctrl-N":f(t,1),"Ctrl-P":f(t,-1),Down:f(t,1),Up:f(t,-1),"Ctrl-A":"goLineStart","Ctrl-E":"goLineEnd",End:"goLineEnd",Home:"goLineStart","Alt-V":f(u,-1),"Ctrl-V":f(u,1),PageUp:f(u,-1),PageDown:f(u,
1),"Ctrl-Up":f(E,-1),"Ctrl-Down":f(E,1),"Alt-A":f(v,-1),"Alt-E":f(v,1),"Alt-K":function(a){m(a,v,1)},"Ctrl-Alt-K":function(a){m(a,l,1)},"Ctrl-Alt-Backspace":function(a){m(a,l,-1)},"Ctrl-Alt-F":f(l,1),"Ctrl-Alt-B":f(l,-1),"Shift-Ctrl-Alt-2":function(a){a.setSelection(z(a,l,1),a.getCursor())},"Ctrl-Alt-T":function(a){var b=l(a,a.getCursor(),-1),c=l(a,b,1),d=l(a,c,1),e=l(a,d,-1);a.replaceRange(a.getRange(e,d)+a.getRange(c,e)+a.getRange(b,c),b,d)},"Ctrl-Alt-U":g(function(a){for(var b=a.getCursor(),c=
b.line,b=b.ch,d=[];c>=a.firstLine();){for(var e=a.getLine(c),f=null==b?e.length:b;0<f;)if(b=e.charAt(--f),")"==b)d.push("(");else if("]"==b)d.push("[");else if("}"==b)d.push("{");else if(/[\(\{\[]/.test(b)&&(!d.length||d.pop()!=b))return a.extendSelection(h(c,f));--c;b=null}}),"Alt-Space":function(a){for(var b=a.getCursor(),c=b.ch,d=b.ch,e=a.getLine(b.line);c&&/\s/.test(e.charAt(c-1));)--c;for(;d<e.length&&/\s/.test(e.charAt(d));)++d;a.replaceRange(" ",h(b.line,c),h(b.line,d))},"Ctrl-O":g(function(a){a.replaceSelection("\n",
"start")}),"Ctrl-T":g(function(a){var b=a.getCursor();b.ch<a.getLine(b.line).length&&(b=h(b.line,b.ch+1));var c=a.findPosH(b,-2,"char"),d=a.getRange(c,b);2==d.length&&(a.setSelection(c,b),a.replaceSelection(d.charAt(1)+d.charAt(0),"end"))}),"Alt-C":g(function(a){B(a,function(a){var c=a.search(/\w/);return-1==c?a:a.slice(0,c)+a.charAt(c).toUpperCase()+a.slice(c+1).toLowerCase()})}),"Alt-U":g(function(a){B(a,function(a){return a.toUpperCase()})}),"Alt-L":g(function(a){B(a,function(a){return a.toLowerCase()})}),
"Alt-;":"toggleComment","Ctrl-/":g("undo"),"Shift-Ctrl--":g("undo"),"Ctrl-Z":g("undo"),"Cmd-Z":g("undo"),"Shift-Alt-,":"goDocStart","Shift-Alt-.":"goDocEnd","Ctrl-S":"findNext","Ctrl-R":"findPrev","Ctrl-G":"clearSearch","Shift-Alt-5":"replace","Alt-/":"autocomplete","Ctrl-J":"newlineAndIndent",Enter:!1,Tab:"indentAuto","Alt-G":function(a){a.setOption("keyMap","emacs-Alt-G")},"Ctrl-X":function(a){a.setOption("keyMap","emacs-Ctrl-X")},"Ctrl-Q":function(a){a.setOption("keyMap","emacs-Ctrl-Q")},"Ctrl-U":function(a){a.state.emacsPrefixMap=
!0;a.addKeyMap(A);a.on("keyHandled",w);a.on("inputRead",w)}};CodeMirror.keyMap["emacs-Ctrl-X"]={Tab:function(a){a.indentSelection(q(a,!0)||a.getOption("indentUnit"))},"Ctrl-X":function(a){a.setSelection(a.getCursor("head"),a.getCursor("anchor"))},"Ctrl-S":"save","Ctrl-W":"save",S:"saveAll",F:"open",U:g("undo"),K:"close",Delete:function(a){r(a,a.getCursor(),v(a,a.getCursor(),1),!0)},auto:"emacs",nofallthrough:!0,disableInput:!0};CodeMirror.keyMap["emacs-Alt-G"]={G:function(a){var b=q(a,!0);if(null!=
b&&0<b)return a.setCursor(b-1);M(a,"Goto line",function(b){var d;b&&(!isNaN(d=Number(b))&&d==d|0&&0<d)&&a.setCursor(d-1)})},auto:"emacs",nofallthrough:!0,disableInput:!0};CodeMirror.keyMap["emacs-Ctrl-Q"]={Tab:g("insertTab"),auto:"emacs",nofallthrough:!0};for(var A={"Ctrl-G":y},C=0;10>C;++C)K(String(C));K("-")})();
